name: CI

on:
  push:
    branches:
      - deploy

env:
  GIT_USER: fireyang
  GIT_EMAIL: shenhuan007@gmail.com
  DEPLOY_REPO: fireyang/fireyang.github.io
  DEPLOY_BRANCH: master

jobs:
  build:
    name: Build on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    strategy:
      matrix:
        node: [14, 16, 18]

    steps:
      - name: Checkout deploy repo
        uses: actions/checkout@v3
        with:
          ref: deploy
          submodules: recursive

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache2
          restore-keys: |
            ${{ runner.OS }}-npm-cache2

      - name: Install Dependencies
        run: yarn

      - name: Build static
        run: yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTION_DEPLOY_KEY }}
          external_repository: fireyang/fireyang.github.io
          publish_branch: master
          publish_dir: ./public
